import assert from 'node:assert/strict'
import { musicReadout } from '../app/src/music-readout'

const candidate = musicReadout({ status: 'listening', bpm: null, candidate_bpm: 118.4, confidence: .22, playing: true }, null, true)
assert.equal(candidate.bpm, 118.4)
assert.equal(candidate.state, 'calculating')
assert.equal(candidate.current, true)
const locked = musicReadout({ status: 'listening', bpm: 120, candidate_bpm: 119, confidence: .8, locked: true }, candidate.bpm, true)
assert.equal(locked.bpm, 120)
assert.equal(locked.state, 'locked')
const dropped = musicReadout({ status: 'listening', bpm: null }, locked.bpm, true)
assert.equal(dropped.bpm, 120)
assert.equal(dropped.state, 'calculating')
assert.equal(dropped.current, false)
assert.match(dropped.detail, /Last estimate/)
assert.equal(musicReadout({ status: 'listening', playing: false }, 120, true).state, 'quiet')
assert.equal(musicReadout({ status: 'listening', bpm: 120, confidence: .9 }, 120, false).state, 'disabled')
const stale = musicReadout({ status: 'listening', bpm: 120, confidence: .9, timestamp: 10 }, 118, true, 100)
assert.equal(stale.state, 'unavailable')
assert.equal(stale.bpm, 118)
assert.equal(stale.current, false)
assert.equal(musicReadout({}, null, true).bpm, null)
assert.equal(musicReadout({ status: 'listening', candidate_bpm: NaN, confidence: Infinity }, null, true).bpm, null)
assert.equal(musicReadout({ status: 'listening', bpm: 120, locked: false, confidence: .8 }, null, true).state, 'calculating')
console.log('Music readout passed: tentative BPM, lock, last estimate, silence, disabled, stale capture, invalid values.')
